### ISSUE TITLE
No schedules shown at all

### ISSUE THREAD

**Issue by micahp2** [paulirish/caltrainschedule.io#59]
As Caltrain has recently changed their schedules, it seems that this site has broken and no longer returns any working results.

**Comment by paulirish** [comment]
really appreciate you filing the ticket, @micahp2 !

it should be fixed now

the site has some caching on it so you'll probably have to reload twice to get the new version. 
the new version says `Oct 7 2019 effective Caltrain schedule, refreshed 10/11/2019.` at the bottom.

**Comment by micahp2** [comment]
Seems that this bug is back. The site is no longer returning any schedules as of 1/17/2020.
